common:
  service_password:
  latitude:          42.56212
  longitude:         -70.84997
  location:          01915
  wunderground:
    01915:                    # location
      id: KMABEVER3           # wunderground id
      password: wx2005
development:
  service_password: wx        # web service passwd
test:
  service_password: wx
production:
  service_password: wx


