common:
  service_password:
  latitude:          42.56212
  longitude:         -70.84997
  location:          01915
development:
  service_password: wx
test:
  service_password: wx
production:
  service_password: wx


