common:
  service_password:
  latitude:          42.56212
  longitude:         -70.84997
  location:          01915
  wunderground:
    01915:
      id: KMASTONE1
      password: wx2005
development:
  service_password: wx
test:
  service_password: wx
production:
  service_password: wx
  memcache_url: 192.168.1.4:11211
  