--- 
:log_file: log/mongrel.log
:debug: false
:pid_file: log/mongrel.pid
:includes: 
- mongrel
:config_file: 
:environment: production
:group: 
:config_script: 
:host: 0.0.0.0
:docroot: public
:user: 
:num_processors: 1024
:port: "3000"
:mime_map: 
:timeout: 0
:cwd: /Users/tom/dev/weather
:prefix: 
:daemon: true
