# app specific settings
# from memcache: app, namespace='config'
#  w = wunderground.Wunderground('KMABEVER3', 'wx2005', 3.0)

locations:
  01915:
    # this is for translating incoming condition posts in the proper TZ on the web page
    tz: America/New_York
    post: True
    upload: True
#    wunderground:
#      station: KMABEVER3
#      password: wx2005
  01915-dev:
    # this is for translating incoming condition posts in the proper TZ on the web page
    tz: America/New_York
    post: True
    upload: True
    wunderground:
      station: KMABEVER3
      password: wx2005
      conditions: False
      archives: True
  WARING:
    tz: America/New_York
